### ISSUE TITLE
Will it connect to TigerVNC server?

### ISSUE THREAD

**Issue by bob-u** [jonshouse1/ESPVNCC#2]
I wonder if this could be used for klipperscreen (for 3d printer display).  Can this client connect to TigerVNC server?

Also, what is the performance like on WIFI?

**Comment by jonshouse1** [comment]
I've not tested it with TigerVNC but it should work.  The WIFI performance seems quite good.

The ESP IDF seems to have a couple of major bugs that cause this project to be unreliable for long term usage (at least with wired networking). I've not left a Wifi session running for long enough to know if that is reliable long term.

I think the Arduino IDE projects do not have the same issues, it is probably a good idea to try one of those first. I've not tried it myself but "arduinoVNC" looks pretty complete and seems to have a good user base.

**Comment by bob-u** [comment]
Reliability is somewhat important since I'm thinking of using it for 3d printer display.  Thanks for the hint on the arduinoVNC.
